name: Build Typst Documentation and Sign PDFs

on:
  push:
    branches:
      - main
    # Ignora i PDF già generati per evitare loop
    paths-ignore:
      - 'documents/**/*.pdf'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout e pull del repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      # 2. Setup della toolchain Rust e installazione di Typst CLI
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Typst
        run: |
          cargo install --locked typst-cli
          typst --version

      # 3. Compilazione dei file .typ in PDF (output in documents/)
      - name: Compile all Typst files
        run: |
          # Trova tutti i file con estensione .typ nella cartella sources
          find sources -type f -name "*.typ" | while read -r file; do
            # Sostituisce 'sources/' con 'documents/' e '.typ' con '.pdf'
            output="documents/$(echo "$file" | sed 's|^sources/||; s|\.typ$|.pdf|')"
            # Crea la cartella di destinazione se non esiste
            mkdir -p "$(dirname "$output")"
            # Compila il file .typ in PDF
            typst compile "$file" "$output"
          done

      # 4. Decodifica del certificato PKCS#12 dal secret e salvataggio in cert.p12
      - name: Decode signing certificate
        run: |
          echo "Decoding certificate into cert.p12..."
          echo "${{ secrets.SIGN_CERT }}" | base64 -d > cert.p12
          ls -l cert.p12

      # 5. Firma digitale dei PDF (solo quelli non ancora firmati)
      - name: Sign PDFs
        env:
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
          JAVA_TOOL_OPTIONS: "--add-opens=java.base/sun.security.pkcs12=ALL-UNNAMED"
        run: |
          for pdf in $(find documents -type f -name "*.pdf"); do
            filename=$(basename "$pdf")
            # Salta i PDF già firmati (che hanno il suffisso _signed)
            if [[ "$filename" == *_signed.pdf ]]; then
              echo "Skipping already signed PDF: $pdf"
              continue
            fi
            echo "Signing $pdf..."
            java -jar jsignpdf-2.3.0/JSignPdf.jar \
              -q \
              -kst PKCS12 \
              -ksf cert.p12 \
              -ksp "$SIGN_CERT_PASSWORD" \
              -ts http://timestamp.digicert.com \
              -os _signed \
              "$pdf"
            signed_pdf="${pdf%.pdf}_signed.pdf"
            if [ -f "$signed_pdf" ]; then
              echo "Successfully signed: $signed_pdf. Removing original $pdf"
              rm "$pdf"
            else
              echo "ERROR: Signing failed for $pdf"
              exit 1
            fi
          done

      # 6. Commit e push dei PDF aggiornati
      - name: Commit and push signed PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Aggiorna PDF con firma digitale"
          git push origin HEAD:main
