name: Build and Sign PDFs

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'documents/**/*.pdf'

permissions:
  contents: write

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download jSignPdf minimal
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget -q "https://sourceforge.net/projects/jsignpdf/files/stable/JSignPdf-2.3.0/jsignpdf-2.3.0.zip/download" -O jsignpdf-2.3.0.zip
          unzip -j jsignpdf-2.3.0.zip "jsignpdf-2.3.0/JSignPdf.jar" -d .
          ls -l JSignPdf.jar

      - name: Download missing libs
        run: |
          mkdir lib
          # BouncyCastle
          wget -q https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.70/bcprov-jdk15on-1.70.jar -O lib/bcprov-jdk15on.jar
          wget -q https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.70/bcpkix-jdk15on-1.70.jar -O lib/bcpkix-jdk15on.jar
          # OpenPDF
          wget -q https://repo1.maven.org/maven2/com/github/librepdf/openpdf/1.3.30/openpdf-1.3.30.jar -O lib/openpdf.jar
          # Commons CLI, IO, Lang
          wget -q https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar -O lib/commons-cli.jar
          wget -q https://repo1.maven.org/maven2/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar -O lib/commons-io.jar
          wget -q https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar -O lib/commons-lang3.jar
          # Se serve PDFBox (dipende dalla build)
          wget -q https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox/2.0.29/pdfbox-2.0.29.jar -O lib/pdfbox.jar
          ls -R lib

      - name: Decode certificate
        run: |
          echo "${{ secrets.SIGN_CERT }}" | base64 -d > cert.p12

      - name: Sign PDFs
        env:
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
          JAVA_TOOL_OPTIONS: "--add-opens=java.base/sun.security.pkcs12=ALL-UNNAMED"
        run: |
          for pdf in $(find documents -type f -name "*.pdf"); do
            echo "Signing $pdf..."
            java -cp "JSignPdf.jar:lib/*" net.sf.jsignpdf.JSignPdf \
              -q \
              -kst PKCS12 \
              -ksf cert.p12 \
              -ksp "$SIGN_CERT_PASSWORD" \
              -ts http://timestamp.digicert.com \
              -os _signed \
              "$pdf"
            signed_pdf="${pdf%.pdf}_signed.pdf"
            if [ -f "$signed_pdf" ]; then
              rm "$pdf"
            else
              echo "ERROR: $pdf not signed"
              exit 1
            fi
          done

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "Signed PDFs"
          git push origin HEAD:main
