name: Build Typst Documentation, Sign PDFs and Commit

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'documents/**/*.pdf'

permissions:
  contents: write

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Set up Rust and Install Typst CLI
        uses: dtolnay/rust-toolchain@stable

      - name: Install Typst CLI
        run: |
          cargo install --locked typst-cli
          typst --version

      - name: Compile Typst files to PDF
        run: |
          find sources -type f -name "*.typ" | while read -r file; do
            output="documents/$(echo "$file" | sed 's|^sources/||; s|\.typ$|.pdf|')"
            mkdir -p "$(dirname "$output")"
            typst compile "$file" "$output"
          done

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Initialize package.json and install dependencies
        run: |
          echo '{ "name": "node-jsignpdf-workflow", "version": "1.0.0" }' > package.json
          npm install jsignpdf node-forge
          cat package.json
          ls -la node_modules

      - name: Run sign.js script
        env:
          SIGN_CERT: ${{ secrets.SIGN_CERT }}
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
        run: node sign.js

      - name: Verify signed PDFs exist
        run: |
          SIGNED_FILES=$(find documents -type f -name "*_signed.pdf")
          if [ -z "$SIGNED_FILES" ]; then
            echo "ERROR: Nessun PDF firmato trovato!"
            exit 1
          else
            echo "DEBUG: PDF firmati trovati:"
            echo "$SIGNED_FILES"
          fi

      - name: Commit and push signed PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/
          if git diff --cached --quiet; then
            echo "DEBUG: No changes to commit"
            exit 0
          fi
          git commit -m "Aggiorna PDF con firma digitale"
          git push origin HEAD:main
