name: Build Typst Documentation, Sign PDFs and Debug

on:
  push:
    branches:
      - main
    # Ignora i PDF già generati per evitare loop
    paths-ignore:
      - 'documents/**/*.pdf'

permissions:
  contents: write

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout e pull del repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      # 2. Setup della toolchain Rust e installazione di Typst CLI
      - name: Set up Rust and Install Typst CLI
        uses: dtolnay/rust-toolchain@stable

      - name: Install Typst CLI
        run: |
          cargo install --locked typst-cli
          typst --version

      # 3. Compilazione dei file .typ in PDF (output in documents/)
      - name: Compile Typst files to PDF
        run: |
          find sources -type f -name "*.typ" | while read -r file; do
            output="documents/$(echo "$file" | sed 's|^sources/||; s|\.typ$|.pdf|')"
            mkdir -p "$(dirname "$output")"
            typst compile "$file" "$output"
          done

      # 4. Debug: List documents folder BEFORE signing
      - name: Debug: List documents folder before signing
        run: |
          echo "DEBUG: Listing documents folder before signing:"
          ls -laR documents

      # 5. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 6. Initialize package.json and install dependencies
      - name: Initialize package.json and install dependencies
        run: |
          echo '{ "name": "node-jsignpdf-workflow", "version": "1.0.0" }' > package.json
          npm install jsignpdf node-forge
          cat package.json
          ls -la node_modules

      # 7. Esegui lo script sign.js per firmare i PDF
      - name: Run sign.js script
        env:
          SIGN_CERT: ${{ secrets.SIGN_CERT }}
          SIGN_CERT_PASSWORD: ${{ secrets.SIGN_CERT_PASSWORD }}
        run: node sign.js

      # 8. Debug: List documents folder AFTER signing
      - name: Debug: List documents folder after signing
        run: |
          echo "DEBUG: Listing documents folder after signing:"
          ls -laR documents

      # 9. Commit e push dei PDF firmati
      - name: Commit and push signed PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documents/
          if git diff --cached --quiet; then
            echo "DEBUG: No changes to commit"
            exit 0
          fi
          git commit -m "Aggiorna PDF con firma digitale"
          git push origin HEAD:main
